[package]
name = "hecto"
version = "0.1.0"
edition = "2018"
authors=["Jacopo De Gattis <jacopo.degattis@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1" # used to enter RAW MODE
